### ISSUE TITLE
Listing: 'View all plants/animals'

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#23]
This button should set the appropriate filters and run the search as per the normal listing page, not open a different page with a different style of layout, fields, etc.

**Comment by rukayaj** [comment]
As discussed, this was put in place because Lize von Staden says people like to use the glossary type search on their red listing site. But I agree it's a bit confusing/unecessary to have two different search result style pages. 

I've exposed the search operator instead (options are: Starts with, contains, ends with, etc). So people can search or Starts with "A" and do essentially the same thing. What do you think of that? And I've removed the "View all" buttons leading to the separate search pages.

**Comment by reupost** [comment]
Would it be possible to adjust the search operator so it only shows 'Starts with' and 'Contains'?  I don't think the other options add much value.  As a side note, entering '*' for a regular expression gives a website error :)

**Comment by rukayaj** [comment]
Wow cool I didn't realise it let you search on regex! But * isn't valid regex so I would expect an error. Try T.st (for T followed by any letter followed by st). It does work.

I really like all of those search operators! So much that I kind of don't want to hide them. I always feel sad at systems which remove advanced options, and I feel like these are hidden fairly discreetly in that drop down and won't startle/upset people too much. 

There doesn't seem to be a default way of removing them, but I think I can do something like https://www.drupal.org/node/2404289 or worst comes to worst use some javascript to get rid of them. If you really think they need to go! :)

**Comment by reupost** [comment]
I remember someone saying they needed a PhD to use SIBIS, so yes, I'm guilty of the same thing.

Ok, its not a train-smash, we can leave them, but the regex error must be trapped (otherwise next time I'm going to put some SQL-injection script into that text box and see what happens, mu-hah-hah!)

**Comment by rukayaj** [comment]
I have the very latest security updates on the views module (which is powering that search) so I am pretty sure it's secure. Do your worst :)
