### ISSUE TITLE
New species publishing

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#35]
The dropdown to save as unpublished as opposed to publishing straight away is likely to be missed by users.  I would suggest either making the default 'save as unpublished' or separating these out into two buttons, especially until the taxon experts are familiar with the system.

In fact, I'd say there is a reasonable argument for an expert updating all the species in their group out of the public view, and only then, once they are happy, for them to be published en masse (potentially by the site administrators).

From meeting with Brenda and Selwyn 11 Oct: yes, taxon leads should be able to publish; taxon experts just to edit/add species but not publish

**Comment by rukayaj** [comment]
Ok I think this issue is sorted. The mechanism is for the site administrators to publish en masse though, not for the taxon leads. Do we need to change this? If so reopen this issue.

Taxon leads will have a single tick box saying published (appears under status/revision info tabs). Default option is for it to be unticked.
