### ISSUE TITLE
Assessments at genus level?

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/ssp#4]

**Comment by rukayaj** [comment]
Actions: Michele Pfab (SANBI) agreed that the Scientific Authority can support with providing information for genus / family links and facilitate bulk editing / multiple species entries linked to genus or family and flag if species is South African.

•	Allow users to add genus or family, and flag whether species is South African. Michelle Pfab needs to tell me how genus/family evaluations differ from species evaluations.

**Comment by reupost** [comment]
This might be a bit of work to implement, but I think its important that the species within a genus / family are listed individually, so that users can find specific taxa and so that the 'sensitive species list' is consistently a list of species, not a mix of species/genera/families.  

As such, the assessment tree for the genus/family would be identical to that of a species: whatever is defined by the assessor at family/genus level would be copied down to each of the individual species within that family/genus, in the manner of a template.  

If any new species are added to a genus/family after the higher level assessment has been conducted they would need the template values assigned to them as well.

What do you think?

**Comment by rukayaj** [comment]
This is quite a complicated thing to implement. How will it work when there's a preexisting assessment? It will overwrite it. We've agreed not prioritise this issue.

**Comment by reupost** [comment]
From the workshop, it seems better that we add functionality to bulk-upload species names with associated (non-assessed) status.  I'll set up a separate issue for that
