### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#43]
At the moment, all logged-in users can add/edit species.  The current setup is right for the Taxon Leads. 
 Taxon Leads will be managing groups of Taxon Experts.  The latter users would have all the same permissions as the Taxon Leads, except for the right to publish.

Both groups need to be able to find and edit/delete their own rebuttals.

**Comment by rukayaj** [comment]
I'm going to leave Taxon experts as just having the authenticated user role rather than a special role.  I've made a new role called Taxon leads. Should Taxon leads be able to edit already published content? And if so should their changes be made as a new revision and an expert would have to come along and validate them? It would be easiest just not to allow them to edit once something has been published I think.

**Comment by rukayaj** [comment]
Seeing as most of the sensitive species are already listed on the site + are published this is problematic actually. 

What do you think, should I import all content as unpublished and then wait for experts to fill in content + leads to publish? I think this isn't a bad idea actually, will be a good/obvious way of keeping track of which species are "done" and which aren't. 

Sorry can't come on skype because it hogs port 80 and xampp won't work. I will work on another issue while I think about this.

**Comment by reupost** [comment]
Ok.  The taxon experts should not be able to publish.  If both taxon leads and taxon experts can edit published content (which is reasonable), the new edits should really only be publishable by the taxon lead.  So upon editing the published status of the taxon would fall away, requiring the taxon lead to republish it.

BUT I don't think we want to get into a complicated workflow (you know how _that_ tends to mushroom! :)).  If you think that would be awkward to achieve or confusing, especially given that we don't have a lot of time, then maybe just allow the taxon leads to edit published content, which won't affect its published status.  If they want the taxon experts to relook at something they can unpublish it which will enable the taxon expert to make edits.  This is not ideal, because it would be preferable to keep the original version published, but it would be ok for now I think.

**Comment by rukayaj** [comment]
I think I can set up a rule which, upon saving of edited content, checks the role of the user, and if they are only a taxon expert it switches the status of the content to unpublished. Shouldn't be too complicated, will let you know if it's not do-able.

**Comment by reupost** [comment]
Cool, sounds good.  If its fiddly we can rely on training the users (most of the experts will be taxon leads themselves, so finessing their permissions is probably not too critical at this point).

**Comment by reupost** [comment]
Re the re-import as unpublished: yes, I think that's a good idea.  If everything is unpublished until its been assessed it also helps avoid SANBI giving the impression that species that were sensitive in 2010 are now not sensitive!

**Comment by rukayaj** [comment]
Ok I've done that rule which checks the user and resets content to unpublished if they're not a taxon lead. It's on the site now.
