### ISSUE TITLE
Show status while editing

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#47]
It would be very useful to display the determined status (sensitive / not sensitive) of a species while editing it (or upon saving at the end, if necessary).

**Comment by rukayaj** [comment]
I've made it so that it displays the determined status after saving. It won't show it in the edit tab, but if you are in edit and click on the view tab it'll show it. 

If we were to show the status as one progresses I'd have to rewrite my PHP code in javascript, and every time we make a change to the logic I'd have to change it in both places. And it's fairly complicated so I'd prefer to avoid that if possible.

What I could do is modify the edit template to show the sensitivity status if there is a status. To be safe I'd budget 2 hours for that? I can probably do it faster but I'm not sure I have done any customisations at all to the admin theme. But I'm not sure if there are more urgent issues I should prioritise.

**Comment by reupost** [comment]
Yes, please adjust edit template to include existing status, that would resolve this nicely (when you save for the first time and the page reloads it would then display the new status, right?)

**Comment by rukayaj** [comment]
When you save for the first time it takes you into view mode which already displays the status. But you can click on edit mode and I've changed it so it will also show you the status in edit mode. 

I also just realised there's no way to tell whether your content is published or not, so i have added a red warning Unpublished content.
