### ISSUE TITLE
Display comments when editing species

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#56]
Is it possible to display the comments (read-only) when editing a species?  Otherwise composing the Rebuttal is tricky since you can't see the relevant comments.

**Comment by rukayaj** [comment]
Hmm I think this is going to be harder than I thought it would because comments are paginated, and there doesn't seem to be a way that I can see of embedding the entire set of comments + pagination. I would have to retrieve them and then manually do all the pagination stuff as well. Do you think a link to the comments opening in a new window would work instead?

**Comment by reupost** [comment]
Yes, that should be ok.  If there are any workflow issues with composing the rebuttals we can always revisit this, but I imagine there will only be a few rebuttals in any event.
