### ISSUE TITLE
Justifications without criteria

### ISSUE THREAD

**Issue by reupost** [rukayaj/ssp#77]
Feedback from user: "If one selects N/A for one of the criteria, and add a justification, the criterion heading does not appear on the species view page, but the justification does, making the information confusing to read. Need to add the selected criteria."

**Comment by rukayaj** [comment]
Ok none of these should allow an N/A option. That was what was originally agreed, people had to select an option (which is why there's an unknown option). I turned on the N/A (i.e. turned off the required field validation) because the bulk import needed it to be off for me to be able to bulk import. Now the bulk import has finished I have made all the radio buttons required again.
